"""Generate `roles_table.c` from the catalogue (factory F12).

    python agent/tools/gen_roles.py --out build/generated/roles_table.c
    python agent/tools/gen_roles.py --in-image http_server_run,dns_server_run --out ...

`kernel/slm/roles.c` keeps its code; only the data comes from here, so a chat
answer cannot drift from what the repo can actually build.

The rule that matters is the `action` pointer. A row only gets one when its
entry symbol is **in this image's slice**, which the caller passes with
`--in-image`. Pointing `action` at a symbol the image does not have gets the
absence stub (`gen_absent.py`), which prints `[ABSENT]` and looks to a user
exactly like the service answering. A dedicated-image row therefore has
`action = 0` and an answer that names the image to build instead.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
CATALOGUE = ROOT / "agent" / "kernel_spec" / "catalogue.yaml"

STATUSES = ("in-image", "dedicated-image", "roadmap", "host-only")
# The C enum roles.c switches on. `CAP_WORKING`/`CAP_ROADMAP` were the only two,
# which is why "a dedicated image does this" could not be said at all.
C_STATUS = {
    "in-image": "CAP_IN_IMAGE",
    "dedicated-image": "CAP_DEDICATED",
    "roadmap": "CAP_ROADMAP",
    "host-only": "CAP_HOST_ONLY",
}


class CatalogueError(Exception):
    pass


def load(path: Path = CATALOGUE) -> list[dict]:
    doc = yaml.safe_load(path.read_text()) or {}
    rows = doc.get("roles") or []
    if not rows:
        raise CatalogueError(f"{path}: no roles")
    seen: set[str] = set()
    for r in rows:
        # A row may cite one path or several; normalising here keeps every
        # caller from having to care which.
        if isinstance(r.get("evidence"), str):
            r["evidence"] = [r["evidence"]]
        for field in ("keyword", "name", "status", "note", "evidence"):
            if not r.get(field):
                raise CatalogueError(f"{r.get('name', '?')}: missing {field!r}")
        if r["status"] not in STATUSES:
            raise CatalogueError(f"{r['name']}: status {r['status']!r} not in {STATUSES}")
        if r["status"] == "in-image" and not r.get("entry"):
            raise CatalogueError(f"{r['name']}: an in-image role needs an entry symbol")
        if r["status"] == "dedicated-image" and not r.get("build"):
            raise CatalogueError(f"{r['name']}: a dedicated-image role must say how to build it")
        if r["status"] == "roadmap" and not r.get("blocked_by"):
            raise CatalogueError(
                f"{r['name']}: a roadmap role must cite what blocks it. "
                f"'Coming soon' is not a status.")
        for k in r["keyword"]:
            if k in seen:
                raise CatalogueError(f"keyword {k!r} appears twice")
            seen.add(k)
    return rows


def escape(text: str) -> str:
    return " ".join(str(text).split()).replace("\\", "\\\\").replace('"', '\\"')


def generate(rows: list[dict], in_image: set[str]) -> str:
    out = [
        "/* GENERATED by agent/tools/gen_roles.py from kernel_spec/catalogue.yaml.",
        " * Do not edit: edit the catalogue, which is checked against the repo by",
        " * agent/tests/unit/test_catalogue.py.",
        " *",
        " * `action` is non-null only where the entry symbol is in THIS image's",
        " * slice. A pointer to an absent symbol resolves to the absence stub,",
        " * which prints [ABSENT] and reads, to a user, exactly like the service",
        " * answering. */",
        '#include "roles.h"',
        "",
    ]
    externs = sorted({r["entry"] for r in rows
                      if r["status"] == "in-image" and r["entry"] in in_image})
    for symbol in externs:
        out.append(f"void {symbol}(void);")
    if externs:
        out.append("")
    out.append("const capability_t auton_caps[] = {")
    for r in rows:
        status = C_STATUS[r["status"]]
        entry = r.get("entry") if r["status"] == "in-image" else None
        action = entry if entry and entry in in_image else "0"
        note = r["note"]
        if r["status"] == "dedicated-image":
            note = f"a dedicated AUTON image does this: {r['build']}. {note}"
        elif r["status"] == "roadmap":
            note = f"not built: {note}"
        for keyword in r["keyword"]:
            out.append(f'\t{{ "{keyword}", "{escape(r["name"])}", {status},')
            out.append(f'\t  "{escape(note)}", {action} }},')
    out.append("};")
    out.append("")
    out.append("const int auton_caps_count = "
               "(int)(sizeof(auton_caps) / sizeof(auton_caps[0]));")
    out.append("")
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=(__doc__ or "").split("\n\n")[0])
    ap.add_argument("--catalogue", type=Path, default=CATALOGUE)
    ap.add_argument("--in-image", default="",
                    help="comma-separated entry symbols this image links")
    ap.add_argument("--out", type=Path)
    args = ap.parse_args(argv)

    rows = load(args.catalogue)
    text = generate(rows, {s for s in args.in_image.split(",") if s})
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(text)
        working = sum(1 for r in rows if r["status"] == "in-image")
        print(f"{args.out}: {len(rows)} role(s), {working} in this image")
    else:
        print(text, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
