"""Emit a service spec from a capability manifest.

This is the join between intent-B (a sentence becomes a manifest) and F2 (the
factory consumes a service spec). It is explicitly a **handoff, not an
implementation**: it writes the factory's existing format rather than inventing
one, and it writes a stub body rather than prose.

    python agent/tools/intent_service.py "I want to play Doom"

The body is deliberately a stub. `dhcp.md` cites RFC 2131 normatively; a
generator that writes plausible-looking protocol prose produces a spec an agent
will implement confidently and wrongly. That is the phantom-PCI-id failure one
layer up, and it is worse here because a spec is treated as authoritative.
"""

from __future__ import annotations

import argparse
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SERVICES = ROOT / "agent" / "kernel_spec" / "services"
sys.path.insert(0, str(Path(__file__).resolve().parent))

from intent_manifest import IntentError, Manifest, build  # noqa: E402
from service_spec import ServiceSpecError, load as load_service  # noqa: E402

STUB_MARKER = "GENERATED STUB — NOT YET IMPLEMENTABLE"


def _front_matter(manifest: Manifest, name: str, entry: str) -> str:
    def lst(xs: list[str]) -> str:
        return "[" + ", ".join(xs) + "]"

    lines = [
        "---",
        f"service: {name}",
        f"requires: {lst(manifest.requires)}",
        f"excludes: {lst(manifest.excludes)}",
        f"entry: {entry}",
        "markers:",
    ]
    lines += [f'  - "{m}"' for m in manifest.markers]
    lines.append(f"assets: {lst(manifest.assets)}")
    lines.append("---")
    return "\n".join(lines)


def _body(manifest: Manifest, name: str, entry: str) -> str:
    """A stub that says what it is and what is missing.

    Every heading `subsystems/*.md` uses is present and empty, so a human fills
    gaps rather than inventing a structure — but nothing is fabricated.
    """
    assumptions = "\n".join(f"- {a}" for a in manifest.assumptions) or "- none"
    return f"""
# {name.replace('-', ' ').title()} Service Specification

> **{STUB_MARKER}**
>
> Generated by `agent/tools/intent_service.py` from the intent
> *{manifest.intent!r}* (rule `{manifest.matched}`). The front-matter above is
> derived and resolves against the capability index. **Everything below is
> empty on purpose.**
>
> A generator that invented protocol behaviour here would produce a document an
> agent implements confidently and wrongly. A hand-written service spec cites
> its protocol standard normatively; this file cites nothing, because it
> knows nothing.
>
> To finish it: fill each section, cite the protocol normatively, and delete
> this block. `service_spec.py --validate` already passes — that checks the
> front-matter, not whether the prose is implementable.

## Overview

_To be written._ What this image is for, and its scope boundary.

## Assumptions carried from the intent

{assumptions}

## Data Structures

_To be written._

## Interface (`kernel/include/{name.replace('-', '_')}.h`)

```c
/* The single serve loop named in the front-matter. */
void {entry}(void);
```

_The rest to be written._

## Behavior

_To be written. Cite the protocol normatively rather than paraphrasing._

## Files

_To be written._

## Dependencies

Capabilities, per the front-matter: {', '.join(manifest.requires)}.

Explicitly excluded: {', '.join(manifest.excludes) or 'nothing'}.

## Acceptance Criteria

1. All {len(manifest.markers)} markers appear on the serial console, in order.
_The rest to be written._
"""


def emit(sentence: str, name: str | None = None, out_dir: Path = SERVICES) -> Path:
    """Write a service spec, or raise. Never leaves an invalid file on disk.

    Validation happens against a temporary copy first: a spec that fails to
    resolve but is sitting in `services/` looks authoritative, and the next
    reader has no way to tell it was rejected.
    """
    manifest = build(sentence)
    name = name or manifest.matched
    entry = f"{name.replace('-', '_')}_serve"
    text = _front_matter(manifest, name, entry) + "\n" + _body(manifest, name, entry)

    with tempfile.TemporaryDirectory() as tmp:
        probe = Path(tmp) / f"{name}.md"
        probe.write_text(text, encoding="utf-8")
        spec = load_service(probe)     # raises ServiceSpecError
        spec.resolve()                 # raises if the slice is contradictory

    out_dir.mkdir(parents=True, exist_ok=True)
    target = out_dir / f"{name}.md"
    target.write_text(text, encoding="utf-8")
    return target


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("sentence", nargs="+")
    ap.add_argument("--name", help="service name; defaults to the matched rule")
    ap.add_argument("--out-dir", default=str(SERVICES))
    args = ap.parse_args(argv)

    try:
        path = emit(" ".join(args.sentence), args.name, Path(args.out_dir))
    except IntentError as exc:
        print(f"DECLINED: {exc}", file=sys.stderr)
        return 1
    except ServiceSpecError as exc:
        print(f"REJECTED (nothing written): {exc}", file=sys.stderr)
        return 1

    spec = load_service(path)
    sl = spec.resolve()
    try:
        shown = path.relative_to(ROOT)
    except ValueError:
        shown = path          # --out-dir outside the repo, e.g. a scratch dir
    print(f"wrote {shown}")
    print(f"  service {spec.service}, entry {spec.entry}, {len(spec.markers)} markers")
    print(f"  resolves to {len(sl.subsystems)} subsystems: {', '.join(sl.subsystems)}")
    print(f"  body is a stub — the front-matter is derived, the prose is not written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
