"""Assemble an intent into a reviewable package.

    AUTON train "I want to host this repo" --output ./repo-host

`<output>/` carries the ISO, the scoped model, the spec subset that generated
it, an installer, and a provenance record.

The PRD's reason for provenance is specific: *"a human must be able to review
generated kernel code without reading it blind."* That means the record has to
say **which spec section each artifact implements**, not merely list files. A
file listing with hashes is a manifest; this is meant to be a review aid.

An intent that cannot be built yet produces a package that **says so**. A
directory missing its ISO looks like a build that half-worked rather than one
that was never possible, and the difference matters to whoever opens it next.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).resolve().parent))

from build_service import GateFailure, build as build_image  # noqa: E402
from target_spec import TargetError, load as load_target  # noqa: E402
from capability_slice import load_specs  # noqa: E402
from intent_manifest import (  # noqa: E402
    IntentError,
    TargetMismatch,
    build as build_manifest,
)
from intent_service import emit as emit_service  # noqa: E402
from service_spec import load as load_service  # noqa: E402

INSTALLER = """\
#!/usr/bin/env bash
# Install this AUTON image to a block device.
#
# Generated by agent/tools/package_image.py. Read PROVENANCE.json to see what
# produced each file here and which spec section it implements.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
ISO="$HERE/image.iso"

[ -f "$ISO" ] || { echo "no image.iso in $HERE — see PROVENANCE.json" >&2; exit 1; }

TARGET="${1:-}"
if [ -z "$TARGET" ]; then
	echo "usage: $0 /dev/diskN" >&2
	echo "  the image is $(du -h "$ISO" | cut -f1); writing it ERASES the target." >&2
	exit 2
fi
[ -b "$TARGET" ] || { echo "$TARGET is not a block device" >&2; exit 2; }

# Deliberately not silent and not defaulted. This erases a disk.
echo "This will ERASE $TARGET and write $ISO."
printf 'Type the device path again to confirm: '
read -r CONFIRM
[ "$CONFIRM" = "$TARGET" ] || { echo "not confirmed" >&2; exit 1; }

dd if="$ISO" of="$TARGET" bs=4m status=progress
sync
echo "written. boot $TARGET to run this image."
"""


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


@dataclass
class Artifact:
    path: str
    produced_by: str
    from_input: str
    sha256: str
    bytes: int
    implements: str = ""


@dataclass
class Package:
    intent: str
    matched_rule: str
    created_at: str
    complete: bool
    blocked_by: str = ""
    artifacts: list[Artifact] = field(default_factory=list)
    spec_sections: list[dict] = field(default_factory=list)
    # What the image was built to run ON. `spec_sections` says what it is FOR,
    # and until D1 there was no format for the other half — so a package could
    # say "this image serves DHCP" and nothing at all about the machine it
    # expects. An image with no stated target records why, because an absent
    # field and a deliberate "no machine in particular" are different claims.
    # What is known about defects in the silicon this image is built for.
    # Empty when no target was stated: there is no machine to ask about.
    errata: dict = field(default_factory=dict)
    # Per-driver verification outcomes, with the three states intact.
    drivers: dict = field(default_factory=dict)
    target: dict = field(default_factory=lambda: {
        "stated": False,
        "why": "no target was stated; this image was built for no machine in "
               "particular, and nothing here records what it assumes",
    })
    assumptions: list[str] = field(default_factory=list)
    leakage: dict = field(default_factory=dict)

    def to_json(self) -> str:
        return json.dumps({
            **{k: v for k, v in asdict(self).items() if k != "artifacts"},
            "artifacts": [asdict(a) for a in self.artifacts],
        }, indent=2)



def train_scoped_model(manifest, workdir: Path, steps: int = 3000) -> tuple[Path | None, str]:
    """Train and export a model scoped to this manifest.

    Returns (path, note). A failure is a note, never an exception: an image
    without a model is a worse image, not a failed package, and the README says
    which one it is.

    Measured in `.claude/PRPs/reports/e2e-intent-scoped-corpus.md`: scoping the
    corpus does not improve answer quality. It is done here for what it does
    control — image content, and not shipping capability claims the image
    cannot honour.
    """
    workdir.mkdir(parents=True, exist_ok=True)
    manifest_path = workdir / "manifest.json"
    manifest_path.write_text(manifest.to_json() + "\n")

    py = str(ROOT / ".venv" / "bin" / "python")
    if not Path(py).exists():
        return None, "no virtualenv interpreter; cannot train"

    steps_and_args = [
        (["SLM/tools/build_corpus.py", "--manifest", str(manifest_path),
          "--output", str(workdir / "corpus.jsonl")], "build the scoped corpus"),
        (["SLM/tools/tokenizer.py", "--input", str(workdir / "corpus.jsonl"),
          "--output", str(workdir / "vocab.json"), "--vocab-size", "1024",
          "--tokenize-to", str(workdir / "tokens.jsonl")], "tokenize"),
        (["SLM/scripts/train.py", "--config", "SLM/configs/chat_tiny.yaml",
          "--dataset", str(workdir / "tokens.jsonl"), "--output", str(workdir),
          "--max-steps", str(steps), "--seq-len", "64", "--batch-size", "8"], "train"),
        (["SLM/scripts/export_auton.py", "--checkpoint", str(workdir / "final.pt"),
          "--vocab", str(workdir / "vocab.json"),
          "--output", str(workdir / "auton-slm.bin")], "export"),
    ]
    for args, what in steps_and_args:
        r = subprocess.run([py, *args], cwd=ROOT, capture_output=True,
                           text=True, timeout=3600)
        if r.returncode != 0:
            tail = (r.stderr or r.stdout).strip().splitlines()[-2:]
            return None, f"could not {what}: {' '.join(tail)[:160]}"

    out = workdir / "auton-slm.bin"
    return (out, f"trained on the scoped corpus, {steps} steps") if out.exists() \
        else (None, "export produced no model")


def _record(out: Path, rel: str, produced_by: str, from_input: str,
            implements: str = "") -> Artifact | None:
    p = out / rel
    if not p.exists():
        return None
    return Artifact(path=rel, produced_by=produced_by, from_input=from_input,
                    sha256=_sha256(p), bytes=p.stat().st_size, implements=implements)


def _record_target(path: Path, out: Path) -> dict:
    """Validate a target definition and reduce it to what provenance needs.

    Validated before anything is copied: the same "nothing invalid reaches
    disk" rule intent-C enforces. A package carrying a target that does not
    parse is worse than one carrying none, because the next reader believes it.
    """
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from target_spec import validate as validate_target

    report = validate_target(path)          # raises TargetError; the caller lets it
    t = report.target
    dest = out / "spec" / "target.md"
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(path, dest)
    return {
        "stated": True,
        "target": t.target,
        "class": t.klass,
        "arch": t.arch,
        "firmware": t.firmware,
        "silicon": dict(t.silicon),
        "platform": dict(t.platform),
        "devices": [{"id": d.id, "role": d.role, "source": d.source}
                    for d in t.devices],
        "absent": list(t.absent),
        "assumptions": list(t.assumptions),
        "verified": report.ok,
        "spec_file": "spec/target.md",
    }


def _record_errata(target, capabilities: set[str], out: Path) -> dict:
    """Join the target's silicon to the errata table and write the result.

    An image is built for a machine; whether that machine has known defects is
    part of what a reviewer needs, and discovering it after the build is the
    expensive end.
    """
    from errata_join import join

    r = join(target, capabilities)
    record = {
        "target": r.target,
        "examined": r.examined,
        "summary": r.summary(),
        "blocking": list(r.blocking),
    }
    if r.unknown_because:
        record["unknown_because"] = r.unknown_because
    if r.inheritance:
        record["inheritance"] = r.inheritance
    if r.report is not None:
        record["documents"] = list(r.report.documents)
        # Never merged into a total. `assess_machine` keeps these separate
        # because an unknown verdict is not a clear one.
        record["unknown_errata"] = [e for e, _why in r.report.unknown]
        record["not_applicable"] = r.report.not_applicable
        if r.report.assessment:
            record["counts"] = r.report.assessment.counts()

    (out / "spec").mkdir(parents=True, exist_ok=True)
    (out / "spec" / "errata.json").write_text(
        json.dumps(record, indent=2) + "\n", encoding="utf-8")
    return record


def _write_errata_module(target, out: Path, from_input: str) -> Artifact | None:
    """assets/errata.bin scoped to the target's silicon. Empty (and valid) when
    no ingested document covers it, which the image reports as not examined."""
    sys.path.insert(0, str(ROOT / "SLM" / "tools"))
    from build_errata_table import build
    from errata_format import pack
    from vendor_ingest import CACHE

    docs, table = build(CACHE, target.silicon)
    (out / "assets").mkdir(parents=True, exist_ok=True)
    (out / "assets" / "errata.bin").write_bytes(pack(docs, table))
    covered = "covered" if table else "not covered by any ingested document"
    return _record(out, "assets/errata.bin", "SLM/tools/build_errata_table.py", from_input,
                   f"errata verdicts for the target's silicon ({covered}); "
                   f"slm.md Errata Module")


def _record_drivers(target, out: Path) -> dict:
    """Run each applicable driver's own verification and write the result.

    The PRD's metric is *"drivers shipped without executable verification: 0"*,
    and a metric with no artifact behind it is an intention. D8 set the
    precedent with `spec/errata.json`.
    """
    from driver_verify import verify

    report = verify(target)
    (out / "spec").mkdir(parents=True, exist_ok=True)
    (out / "spec" / "drivers.json").write_text(
        report.to_json() + "\n", encoding="utf-8")
    return json.loads(report.to_json())


def package(sentence: str, out: Path, tree: Path, service: str | None = None,
            model: Path | None = None, train: bool = False,
            target: Path | None = None) -> Package:
    # Match the intent BEFORE creating anything. A declined sentence used to
    # leave an empty out/spec/ behind, which is the same "nothing invalid
    # reaches disk" rule intent-C enforces — an empty package directory looks
    # like a build that produced nothing rather than one that never started.
    # Loaded before the intent is matched, so the driver decision can be made
    # from the machine rather than assumed. An invalid target stops everything
    # here — nothing invalid reaches disk, and nothing is built for a machine
    # whose definition does not parse.
    loaded_target = load_target(target) if target is not None else None
    manifest = build_manifest(sentence, target=loaded_target)

    out.mkdir(parents=True, exist_ok=True)
    (out / "spec").mkdir(exist_ok=True)
    pkg = Package(intent=sentence, matched_rule=manifest.matched,
                  created_at=datetime.now(timezone.utc).isoformat(timespec="seconds"),
                  complete=False, assumptions=list(manifest.assumptions))

    if target is not None:
        pkg.target = _record_target(target, out)
        # Reported before the build, not after. The PRD asks for applicable
        # errata to reach a reader while the image is still a decision.
        pkg.errata = _record_errata(loaded_target, set(manifest.requires), out)
        # Written whenever a target is stated, not only when a build succeeds.
        # Which drivers an image needs follows from the machine it is built for,
        # and an INCOMPLETE package still made that claim.
        pkg.drivers = _record_drivers(loaded_target, out)
        pkg.artifacts.append(_record(
            out, "spec/target.md", "authored", str(target),
            "the machine this image was built to run on"))
        # H13: the same verdicts, compiled for the running image to look up by
        # its own silicon identity. A separate module, so errata can be updated
        # without touching the model (slm.md "Errata Module").
        pkg.artifacts.append(_write_errata_module(loaded_target, out, str(target)))

    (out / "spec" / "manifest.json").write_text(manifest.to_json() + "\n")
    pkg.artifacts.append(_record(out, "spec/manifest.json", "intent_manifest.py",
                                 f"intent: {sentence!r}",
                                 "the capability manifest the image is scoped to"))

    # The spec subset: every subsystem spec the slice selected, and why.
    from capability_slice import capability_slice
    sl = capability_slice(manifest.requires, manifest.excludes)
    specs = load_specs()
    for name in sl.subsystems:
        src = specs[name].path
        dest = out / "spec" / "subsystems" / src.name
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dest)
        provided = sorted(set(specs[name].provides) & set(sl.capabilities))
        pkg.spec_sections.append({
            "subsystem": name,
            "included_because": provided or ["a dependency of another subsystem"],
        })
        pkg.artifacts.append(_record(
            out, f"spec/subsystems/{src.name}", "capability_slice.py",
            f"slice of {sentence!r}",
            f"provides {', '.join(provided)}" if provided else
            "included as a transitive dependency"))

    if model is not None:
        note = ("supplied with --model" if Path(model).exists()
                else f"--model {model} does not exist")
    elif train:
        model, note = train_scoped_model(manifest, out / "model" / "work")
    else:
        note = "not requested; pass --train to train one, or --model to supply one"
    if model and Path(model).exists():
        (out / "model").mkdir(exist_ok=True)
        dest_name = Path(model).name
        shutil.copy2(model, out / "model" / dest_name)
        shutil.copy2(out / "spec" / "manifest.json", out / "model" / "manifest.json")
        pkg.artifacts.append(_record(
            out, f"model/{dest_name}", "export_auton.py", note,
            "the on-device model this image answers from"))
        pkg.artifacts.append(_record(
            out, "model/manifest.json", "intent_manifest.py", "intent",
            "the manifest this model was scoped to — kept beside it so the two "
            "cannot be separated"))
        # The training work directory is large and is not the deliverable.
        shutil.rmtree(out / "model" / "work", ignore_errors=True)
    else:
        pkg.assumptions.append(
            f"model: none packaged ({note}). The image falls back to the "
            f"kernel's rule engine, which answers device and system questions "
            f"but not free-form ones.")


    # The service spec, if this intent maps to a buildable service.
    service_name = service
    if service_name is None:
        candidate = ROOT / "agent" / "kernel_spec" / "services" / f"{manifest.matched}.md"
        service_name = manifest.matched if candidate.exists() else None

    if service_name is None:
        pkg.blocked_by = (
            f"no service spec for {manifest.matched!r}. intent_service.py can emit "
            f"a stub, but a stub is not implementable — see "
            f"kernel_spec/services/README.md"
        )
        _finish(out, pkg)
        return pkg

    spec_src = ROOT / "agent" / "kernel_spec" / "services" / f"{service_name}.md"
    shutil.copy2(spec_src, out / "spec" / spec_src.name)
    pkg.artifacts.append(_record(out, f"spec/{spec_src.name}", "authored",
                                 "human or agent", "the service this image runs"))

    try:
        result = build_image(service_name, tree, make_iso=True,
                             target=loaded_target)
    except GateFailure as exc:
        pkg.blocked_by = str(exc)
        _finish(out, pkg)
        return pkg

    iso = tree / f"build-{service_name}" / "auton.iso"
    if iso.exists():
        shutil.copy2(iso, out / "image.iso")
        pkg.artifacts.append(_record(
            out, "image.iso", "build_service.py",
            f"{spec_src.name} + {len(result.sources)} sources",
            f"the bootable image; entry {load_service(spec_src).entry}"))

    if result.leakage_report and Path(result.leakage_report).exists():
        pkg.leakage = json.loads(Path(result.leakage_report).read_text())


    (out / "install.sh").write_text(INSTALLER)
    (out / "install.sh").chmod(0o755)
    pkg.artifacts.append(_record(out, "install.sh", "package_image.py",
                                 "template", "writes image.iso to a block device"))

    pkg.complete = (out / "image.iso").exists()
    if not pkg.complete and not pkg.blocked_by:
        pkg.blocked_by = "the build produced no ISO"
    _finish(out, pkg)
    return pkg


def _finish(out: Path, pkg: Package) -> None:
    pkg.artifacts = [a for a in pkg.artifacts if a is not None]
    (out / "PROVENANCE.json").write_text(pkg.to_json() + "\n")
    status = "COMPLETE" if pkg.complete else "INCOMPLETE"
    lines = [
        f"# AUTON image: {pkg.intent}",
        "",
        f"**{status}**" + (f" — {pkg.blocked_by}" if pkg.blocked_by else ""),
        "",
        f"Matched intent rule `{pkg.matched_rule}`, built {pkg.created_at}.",
        "",
        "## What is here",
        "",
    ]
    for a in pkg.artifacts:
        lines.append(f"- `{a.path}` — {a.implements or 'no description'} "
                     f"({a.bytes:,} bytes, produced by {a.produced_by})")
    if not pkg.complete:
        lines += ["", "## What is missing", "",
                  f"This package is incomplete. {pkg.blocked_by}", "",
                  "It is recorded as incomplete rather than shipped as a partial "
                  "directory, because a directory missing its ISO looks like a "
                  "build that half-worked rather than one that was never possible."]
    if pkg.assumptions:
        lines += ["", "## Assumptions applied", ""]
        lines += [f"- {a}" for a in pkg.assumptions]
    (out / "README.md").write_text("\n".join(lines) + "\n")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("sentence", nargs="+")
    ap.add_argument("--output", required=True)
    ap.add_argument("--tree", default="kernels/x86_64")
    ap.add_argument("--service")
    ap.add_argument("--model", help="use this model instead of training one")
    ap.add_argument("--train", action="store_true",
                    help="train a model scoped to this intent (minutes)")
    ap.add_argument("--target", metavar="FILE",
                    help="the target definition this image is built for "
                         "(agent/kernel_spec/targets/*.md)")
    args = ap.parse_args(argv)

    tree = Path(args.tree)
    if not tree.is_absolute():
        tree = ROOT / tree

    try:
        pkg = package(" ".join(args.sentence), Path(args.output), tree,
                      args.service, Path(args.model) if args.model else None,
                      train=args.train,
                      target=Path(args.target) if args.target else None)
    except IntentError as exc:
        print(f"DECLINED: {exc}", file=sys.stderr)
        return 1
    except TargetMismatch as exc:
        # The sentence is fine and the target is valid; the pairing is not.
        print(f"MISMATCH: {exc}", file=sys.stderr)
        return 2
    except TargetError as exc:
        # A package carrying a target that does not parse is worse than one
        # carrying none: the next reader believes it.
        print(f"INVALID TARGET: {exc}", file=sys.stderr)
        return 1

    print(f"{'COMPLETE' if pkg.complete else 'INCOMPLETE'}: {args.output}")
    for a in pkg.artifacts:
        print(f"  {a.path:38s} {a.bytes:>10,d} B  {a.produced_by}")
    if pkg.blocked_by:
        print(f"  blocked: {pkg.blocked_by}")
    return 0 if pkg.complete else 1


if __name__ == "__main__":
    raise SystemExit(main())
