"""Golden fixtures for the SSH host suite, built from the RFCs independently.

    python tests/kernel/ssh_fixtures/make_fixtures.py

`openssh_client_hello.bin` is a recording of a real OpenSSH client's first bytes
(version string + KEXINIT), captured against a listener that answered only with
a version string. Everything else here is derived from it by this script, which
implements RFC 4253's encodings a second time, in another language, so the C
under test is checked against an independent implementation rather than against
itself.
"""

from __future__ import annotations

import hashlib
import json
import struct
from pathlib import Path

HERE = Path(__file__).resolve().parent
V_S = b"SSH-2.0-AUTON_0.1"


def string(b: bytes) -> bytes:
    return struct.pack(">I", len(b)) + b


def mpint(v: int) -> bytes:
    if v == 0:
        return struct.pack(">I", 0)
    n = v.to_bytes((v.bit_length() + 7) // 8, "big")
    if n[0] & 0x80:            # keep it positive
        n = b"\x00" + n
    return string(n)


def split_client_hello(data: bytes) -> tuple[bytes, bytes]:
    """(V_C without CR LF, the KEXINIT payload including its message number)."""
    line, rest = data.split(b"\r\n", 1)
    (packet_len,) = struct.unpack(">I", rest[:4])
    padding_len = rest[4]
    payload = rest[5:4 + packet_len - padding_len]
    assert payload[0] == 20, f"expected SSH_MSG_KEXINIT (20), got {payload[0]}"
    return line, payload


def main() -> None:
    hello = (HERE / "openssh_client_hello.bin").read_bytes()
    v_c, i_c = split_client_hello(hello)

    # A server KEXINIT offering exactly what ssh.md allows. cookie is fixed so
    # the fixture is reproducible; a real server's is random.
    cookie = bytes(range(16))
    lists = [b"curve25519-sha256", b"ssh-ed25519",
             b"chacha20-poly1305@openssh.com", b"chacha20-poly1305@openssh.com",
             b"", b"", b"none", b"none", b"", b""]
    i_s = bytes([20]) + cookie + b"".join(string(x) for x in lists) + b"\x00" + struct.pack(">I", 0)

    # Fixed, obviously-not-secret values: this fixture proves the ENCODING of
    # the hash input, not a key exchange.
    k_s = string(b"ssh-ed25519") + string(bytes(range(32)))
    q_c = bytes(range(32, 64))
    q_s = bytes(range(64, 96))
    k = int.from_bytes(bytes([0x80]) + bytes(range(31)), "big")   # high bit set: mpint pads

    h_input = (string(v_c) + string(V_S) + string(i_c) + string(i_s) +
               string(k_s) + string(q_c) + string(q_s) + mpint(k))
    (HERE / "exchange_hash_input.bin").write_bytes(h_input)
    (HERE / "server_kexinit.bin").write_bytes(i_s)

    meta = {
        "note": "generated by make_fixtures.py from openssh_client_hello.bin; see ssh.md",
        "v_c": v_c.decode(),
        "v_s": V_S.decode(),
        "client_kexinit_bytes": len(i_c),
        "server_kexinit_bytes": len(i_s),
        "k_hex": f"{k:x}",
        "exchange_hash_input_sha256": hashlib.sha256(h_input).hexdigest(),
        "mpint_of_k_hex": mpint(k).hex(),
    }
    (HERE / "exchange_hash.json").write_text(json.dumps(meta, indent=1) + "\n")
    print(f"H input {len(h_input)} bytes, SHA-256 {meta['exchange_hash_input_sha256']}")


if __name__ == "__main__":
    main()
